############################################################
# Launcher for Blast container for the eBioKit
# This is a template, the following values must be replaced:
#   - $${INSTANCE_NAME}, name for the instance
#   - ${INSTANCE_PORT_1}, port number 1 for the instance (nginx)
#   - ${INSTANCE_PORT_2}, port number 2 for the instance (Sequenceserver)
#   - ${INSTANCE_PORT_3}, port number 3 for the instance (FTP server)
#   - ${ADMIN_USER}, name for admin user
#   - ${ADMIN_PASS}, password for admin user
#   - ${MAX_FILE_SIZE}, max file size for normal upload (no FTP, in MB)
#   - ${FTP_USER}, name for ftp user
#   - ${FTP_PASS}, password for ftp user
############################################################

version: '2'
services:

    $${INSTANCE_NAME}-blast:
      image: fikipollo/blast:0.9
      container_name: $${INSTANCE_NAME}-blast
      environment:
        - ADMIN_USER=${ADMIN_USER}
        - ADMIN_PASS=${ADMIN_PASS}
        - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      depends_on:
        - $${INSTANCE_NAME}-data
      volumes_from:
        - $${INSTANCE_NAME}-data
      ports:
        - "${INSTANCE_PORT_1}:80"
        - "${INSTANCE_PORT_2}:4567"

    $${INSTANCE_NAME}-vsftpd:
      image: fikipollo/vsftpd:0.9
      container_name: $${INSTANCE_NAME}-vsftpd
      environment:
        - FTP_USER=${FTP_USER}
        - FTP_PASS=${FTP_PASS}
        - ONLY_UPLOAD=YES
        - PASV_ENABLE=NO
        - FTP_HOME=/raw
        - UMASK=000
      depends_on:
        - $${INSTANCE_NAME}-data
      volumes_from:
        - $${INSTANCE_NAME}-data
      ports:
        - "${INSTANCE_PORT_3}:21"

    $${INSTANCE_NAME}-data:
      image: busybox
      container_name: $${INSTANCE_NAME}-data
      volumes:
        - ${DATA_LOCATION}/$${INSTANCE_NAME}-data/db:/db
        - ${DATA_LOCATION}/$${INSTANCE_NAME}-data/raw:/raw
        - ${DATA_LOCATION}/$${INSTANCE_NAME}-data/tmp:/tmp
