############################################################
# Launcher for Blast container for the eBioKit
# This is a template, the following values must be replaced:
#   - $${INSTANCE_NAME}, name for the instance
#   - $${INSTANCE_PORT_1}, port number for the instance
# TODO:
# - Webservice + docker for makeblastdb
# - Sequenceserver logs
# - Organize databases in folders? (genomic, protein...)
############################################################

version: '2'
services:

    $${INSTANCE_NAME}-blast:
      image: ebiokit/blast
      container_name: $${INSTANCE_NAME}-blast
      depends_on:
        - $${INSTANCE_NAME}-data
      volumes_from:
        - $${INSTANCE_NAME}-data
      ports:
        - "$${INSTANCE_PORT_1}:4567"

    $${INSTANCE_NAME}-data:
      image: busybox
      container_name: $${INSTANCE_NAME}-data
      volumes:
        - /data/$${INSTANCE_NAME}-data/db:/db
